version: "3"
services:
  api:
    build:
      context: ./src/backend/
    ports:
      - 3333:3333/tcp
    environment:
      NODE_ENV: production
    networks:
      - default
  # redis-cache:
  #   image: "redis:latest"
  #   ports:
  #     - 6379:6379/tcp
  #   networks:
  #     - default

networks:
  default:
    ipam: 
      driver: default
